language: node_js
node_js:
  - "node"
  - "lts/*"
after_script:
    - cat /home/travis/build/matt-coles/js-query-string/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf /home/travis/build/matt-coles/js-query-string/coverage/
